spring.application.name=justmakeit

# Configuration H2 (Base de données en mémoire pour le dev)
spring.datasource.url=jdbc:h2:mem:justmakeitdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false